name: build

on: push

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Install dependencies
        run: npm install -g @frost-beta/huggingface

      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          yarn
          yarn prepack

          huggingface download mlx-community/Meta-Llama-3-8B-Instruct-4bit
          echo Hello | node dist/chat.js Meta-Llama-3-8B-Instruct-4bit

          huggingface download frost-beta/Llama3-33.5M-Japanese
          node dist/generate.js Llama3-33.5M-Japanese

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set package version
        run: |
          npm config set git-tag-version=false
          npm version $VERSION

      - name: Install deps
        run: yarn

      - name: Publish npm package
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
